#server:
#  port: 8080
#
#
## database 연동 설정
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    #    각자 PC에 만들어놓은 Database이름을 써야 합니다.
#
#    url: jdbc:mysql://localhost:3307/festival?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    #    mysql에 생성한 사용자 계정 정보를 써야 합니다.
#    username: root
#    password: 1234
#  thymeleaf:
#    cache: false
#
#  # spring data jpa 설정
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: update # 테이블이 update만 된다. create로 하면 테이블이 실행될때마다 다시 만들어진다.


#h2 db testcode for 민석
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#  spring:
#    session:
#      store-type: jdbc



spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/te;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update #애플리케이션 실행 시점에 내가 가지고 있는 테이블 지우고 다시 테이블 생성     none은 지워지진X
    properties:
      hibernate:
        #       show_sql: true system out으로 출력
        format_sql: true
        default_batch_fetch_size: 100 #인쿼리의 갯수

logging:
  level:
    org.hibernate.SQL: debug #logger로 출력
#    org.hibernate.type: trace
